# Generated by Django 3.0.7 on 2020-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200626_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(default='https://i.ibb.co/yyS6tkd/12.jpg'),
            preserve_default=False,
        ),
    ]
