# Generated by Django 3.0.7 on 2020-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.CharField(default='fa fa-amazon', max_length=100),
            preserve_default=False,
        ),
    ]
