# Generated by Django 3.0.7 on 2020-06-27 16:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iconcolor',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
