# Generated by Django 2.2 on 2020-07-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200710_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
