# Generated by Django 2.2 on 2020-07-11 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_similaritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='similar_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SimilarItems'),
        ),
    ]
