# Generated by Django 2.2 on 2020-07-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_similar_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='similar_items',
        ),
        migrations.AddField(
            model_name='item',
            name='similar_items',
            field=models.ManyToManyField(to='core.SimilarItems'),
        ),
    ]
