# Generated by Django 2.2 on 2020-07-11 06:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200711_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritems',
            name='iconcolor',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
